version: 1.0.{build}
configuration: Release
image: Visual Studio 2015
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
before_build:
- cmd: nuget restore
build:
  project: ZebraDeploy.sln
  verbosity: normal
artifacts:
- path: src\ZebraDeploy.Service\bin\Release
  name: release-rtifacts
  type: zip